package View;

import daoImpl.CompraDaoImpl;
import daoImpl.ProveedorDaoImpl;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Compra;
import model.Proveedor;

public class JimCompra extends javax.swing.JInternalFrame {

    private CompraDaoImpl crudCompra;
    private DefaultTableModel modelo;
    private final Object[] filaDatos;
    private ProveedorDaoImpl IDaoProveedor;

    public JimCompra() {
        initComponents();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.setSize(ancho, alto - 106);
        crudCompra = new CompraDaoImpl();
        modelo = new DefaultTableModel();
        filaDatos = new Object[6];
        IDaoProveedor = new ProveedorDaoImpl();
        listarCompras();
    }

    private void limpiarTabla() {
        modelo = (DefaultTableModel) tblCompras.getModel();
        modelo.setRowCount(0);
    }

    public void listarCompras() {
        limpiarTabla();
        modelo = (DefaultTableModel) tblCompras.getModel();
        for (Compra com : crudCompra.listar()) {
            if (com != null && com.isEstado() == true) {
                filaDatos[0] = com.getIdCompra();
                filaDatos[1] = com.getFecha();
                for (Proveedor pro : IDaoProveedor.listar()) {
                    if (pro != null && pro.getIdProveedor() == com.getIdProveedor()) {
                        filaDatos[2] = pro.getNombres() + " " + pro.getApellidos();
                    }
                }
                filaDatos[3] = com.getSubTotal();
                filaDatos[4] = com.getImpuestoTotal();
                filaDatos[5] = com.getTotal();
                modelo.addRow(filaDatos);
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEditarDetalle = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBuscarCompra = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnVerDetalle = new javax.swing.JButton();
        btnGenerarDetalleCompra = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditarDetalle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEditarDetalle.setText("Editar detalle");
        btnEditarDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDetalleActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, -1, 31));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Buscar:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setText("Compras");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        txtBuscarCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarCompraActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 332, 30));

        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Proveedor", "Subtotal", "Total impuestos", "Total"
            }
        ));
        tblCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblComprasMouseReleased(evt);
            }
        });
        tblCompras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblComprasKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tblCompras);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 1136, 340));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 120, -1, 30));

        btnVerDetalle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnVerDetalle.setText("Ver detalle");
        btnVerDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetalleActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 120, 30));

        btnGenerarDetalleCompra.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnGenerarDetalleCompra.setText("Nuevo");
        btnGenerarDetalleCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarDetalleCompraActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerarDetalleCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDetalleActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tblCompras.getSelectedRow();

        if (filaSeleccionada != -1) { // Verifica si hay una fila seleccionada
            // Obtén el ID de la compra desde la columna correspondiente
            Object value = tblCompras.getValueAt(filaSeleccionada, 0);
            if (value instanceof Integer) {
                int idCompra = (Integer) value;
                // Abre la ventana de detalle con los datos de la compra
                FrmMenu menu = (FrmMenu) SwingUtilities.getWindowAncestor(this);  // Obtén la ventana principal
                JDesktopPane jDesktopPane_menu = menu.getDesktopPane();  // Accede al JDesktopPane

                // Crear la vista de detalles de compra
                JimDetalleCompra vistaDCompras = new JimDetalleCompra();

                // Pasa el ID de la compra a la vista de detalles
                vistaDCompras.cargarDatosCompraEditar(idCompra);  // Método que carga los datos

                if (jDesktopPane_menu != null) {
                    jDesktopPane_menu.add(vistaDCompras); // Agrega el JInternalFrame al JDesktopPane
                    vistaDCompras.setVisible(true); // Haz visible el JInternalFrame

                    try {
                        vistaDCompras.setSelected(true); // Selecciona el JInternalFrame
                    } catch (java.beans.PropertyVetoException e) {
                        e.printStackTrace();
                    }
                } else {
                    System.out.println("El JDesktopPane no está inicializado.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "El valor de la columna ID no es válido.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una compra de la tabla.");
        }
    }//GEN-LAST:event_btnEditarDetalleActionPerformed

    private void txtBuscarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCompraActionPerformed

    private void btnGenerarDetalleCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarDetalleCompraActionPerformed
        // TODO add your handling code here:
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        FrmMenu menu = (FrmMenu) SwingUtilities.getWindowAncestor(this);  // Obtiene la ventana principal (FrmMenu)
        JDesktopPane jDesktopPane_menu = menu.getDesktopPane();  // Accede al JDesktopPane

        // Crear la vista de detalles de compra
        JimDetalleCompra vistaDCompras = new JimDetalleCompra();

        // Asegúrate de que jDesktopPane_menu no sea null
        if (jDesktopPane_menu != null) {
            // Agregar el JInternalFrame (vistaDCompras) al JDesktopPane
            jDesktopPane_menu.add(vistaDCompras);

            // Hacer visible el JInternalFrame
            vistaDCompras.setVisible(true);

            // Establecer el JInternalFrame en el centro
            try {
                vistaDCompras.setSelected(true);  // Asegura que esté al frente
            } catch (java.beans.PropertyVetoException e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("El JDesktopPane no está inicializado.");
        }
    }//GEN-LAST:event_btnGenerarDetalleCompraActionPerformed

    private void btnVerDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleActionPerformed
        int filaSeleccionada = tblCompras.getSelectedRow();

        if (filaSeleccionada != -1) { // Verifica si hay una fila seleccionada
            // Obtén el ID de la compra desde la columna correspondiente
            Object value = tblCompras.getValueAt(filaSeleccionada, 0);
            if (value instanceof Integer) {
                int idCompra = (Integer) value;
                // Abre la ventana de detalle con los datos de la compra
                FrmMenu menu = (FrmMenu) SwingUtilities.getWindowAncestor(this);  // Obtén la ventana principal
                JDesktopPane jDesktopPane_menu = menu.getDesktopPane();  // Accede al JDesktopPane

                // Crear la vista de detalles de compra
                JimDetalleCompra vistaDCompras = new JimDetalleCompra();

                // Pasa el ID de la compra a la vista de detalles
                vistaDCompras.cargarDatosCompra(idCompra);  // Método que carga los datos

                if (jDesktopPane_menu != null) {
                    jDesktopPane_menu.add(vistaDCompras); // Agrega el JInternalFrame al JDesktopPane
                    vistaDCompras.setVisible(true); // Haz visible el JInternalFrame

                    try {
                        vistaDCompras.setSelected(true); // Selecciona el JInternalFrame
                    } catch (java.beans.PropertyVetoException e) {
                        e.printStackTrace();
                    }
                } else {
                    System.out.println("El JDesktopPane no está inicializado.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "El valor de la columna ID no es válido.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una compra de la tabla.");
        }


    }//GEN-LAST:event_btnVerDetalleActionPerformed

    private void tblComprasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComprasMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblComprasMouseReleased

    private void tblComprasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblComprasKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblComprasKeyReleased

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tblCompras.getSelectedRow();

        if (filaSeleccionada != -1) { // Verifica si hay una fila seleccionada
            // Obtén el ID de la compra desde la columna correspondiente
            Object value = tblCompras.getValueAt(filaSeleccionada, 0);
            if (value instanceof Integer) {
                int idCompra = (Integer) value;

                // Mostrar cuadro de confirmación
                int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar esta compra?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

                if (confirmacion == JOptionPane.YES_OPTION) {
                    // Crear un objeto Compra solo con el idCompra
                    Compra compraAEliminar = new Compra();
                    compraAEliminar.setIdCompra(idCompra);

                    // Llamar al método eliminar
                    if (crudCompra.eliminar(compraAEliminar)) {
                        JOptionPane.showMessageDialog(this, "Compra eliminada con éxito.");
                        limpiarTabla();
                        listarCompras();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo eliminar la compra.");
                    }
                } else {
                    // Si el usuario selecciona 'No'
                    JOptionPane.showMessageDialog(this, "Eliminación cancelada.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "El valor de la columna ID no es válido.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una compra de la tabla.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarDetalle;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerarDetalleCompra;
    private javax.swing.JButton btnVerDetalle;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblCompras;
    private javax.swing.JTextField txtBuscarCompra;
    // End of variables declaration//GEN-END:variables
}
