package View;

import daoImpl.GananciaDaoImpl;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Nodo;

public class JimGanancia extends javax.swing.JInternalFrame {
    GananciaDaoImpl crudGanancia = new GananciaDaoImpl();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d-M-yyyy");
    float gananciaHoy = 0.f;
    String fechaFormateada = "";
    
    public JimGanancia() {
        initComponents();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.setSize(ancho, alto-106);
        crudGanancia.cargarDatosVenta();
    }
    
    public void preOrder(Nodo nodo_root) {
        // preOrder
        if (nodo_root != null) {
            gananciaHoy += nodo_root.getVenta().getTotal();
            preOrder(nodo_root.getIzquierdo());
            preOrder(nodo_root.getDerecho());
        }
    }
    
    public String devolverFechaHoy() {
        LocalDate fechaActual = LocalDate.now();
        return fechaActual.format(formatter);
    }
    
    public void mostrarHoy(Nodo nodo_root) {
        // inOrder
        DecimalFormat df = new DecimalFormat("0.00");
        if (nodo_root != null) {
            mostrarHoy(nodo_root.getIzquierdo());
            String fechaExtraida = nodo_root.getVenta().getFecha().split(" ")[0];
            if (fechaExtraida.equalsIgnoreCase(fechaFormateada) && nodo_root.getVenta().isEstado() == true) {
                gananciaHoy += nodo_root.getVenta().getTotal();
            }
            mostrarHoy(nodo_root.getDerecho());
        }
        if (gananciaHoy == 0.0f) {
            lblResultado.setText("No hay ganancias en la fecha seleccionada.");
        } else {
            lblResultado.setText("La ganancia de hoy es "+gananciaHoy);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Ganancias");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("FECHA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 60, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Resultado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, 30));

        btnMostrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, 30));

        lblResultado.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 250, 30));
        getContentPane().add(jdcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        Date fechaSelecionada = jdcFecha.getDate();
        gananciaHoy = 0.0f;
        if (fechaSelecionada != null) {
            SimpleDateFormat formatter = new SimpleDateFormat("d-M-yyyy");
            fechaFormateada = formatter.format(fechaSelecionada);
            mostrarHoy(crudGanancia.nodoGananciaPrincipal);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fecha.");
        }
    }//GEN-LAST:event_btnMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
}
