package View;

import daoImpl.UsuarioDoalmpl;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Usuario;

public class JimUsuario extends javax.swing.JInternalFrame {

    private UsuarioDoalmpl crudUsuario = new UsuarioDoalmpl();
    private DefaultTableModel modelo;
    private Object[] filaDatos;
    private int idUsuario;
    private boolean guardar = false;

    public JimUsuario() {
        initComponents();
        filaDatos = new Object[2];
        modelo = new DefaultTableModel();
        habilitarCampo(false);
        crudBotones(false);
        registroBotones(false);
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.setSize(ancho, alto - 106);
                listarUsuario();

    }

    private void listarUsuario() {
        btnSize.setEnabled(true);
        btnEmpty.setEnabled(true);
        modelo = (DefaultTableModel) tblUsuarios.getModel();
        for (Usuario c : crudUsuario.listar()) {

            if (c != null) {
                filaDatos[0] = c.getIdUsuario();
                filaDatos[1] = c.getUsuario();
                modelo.addRow(filaDatos);
            }

        }
        if (crudUsuario.size() > 1) {
            txtBuscar.setEnabled(true);
        } else {
            txtBuscar.setEnabled(true);
        }

        if (crudUsuario.size() > 0) {
            btnClear.setEnabled(true);
            btnPeek.setEnabled(true);
            btnPop.setEnabled(true);
        } else {
            btnCancelar.setEnabled(false);
            btnPeek.setEnabled(false);
        }

    }

    private void limpiarTabla() {
        modelo = (DefaultTableModel) tblUsuarios.getModel();
        modelo.getDataVector().removeAllElements();
        tblUsuarios.removeAll();
    }

    private void habilitarCampo(boolean f) {
        txtBuscar.setText("");
        txtNombreUsuario.setEnabled(f);
        txtContrasena.setEnabled(f);
        txtNombreUsuario.requestFocus();
    }

    private void crudBotones(boolean f) {
        btnEditar.setEnabled(f);
        btnEliminar.setEnabled(f);
        btnNuevo.setEnabled(!f);

    }

    private void registroBotones(boolean f) {
        btnCancelar.setEnabled(f);
        btnPeek.setEnabled(f);
        btnPop.setEnabled(f);
        btnPush.setEnabled(f);

    }

    private void limpiarCajas() {
        txtNombreUsuario.setText("");
        txtContrasena.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        btnPush = new javax.swing.JButton();
        btnPop = new javax.swing.JButton();
        btnPeek = new javax.swing.JButton();
        btnSize = new javax.swing.JButton();
        btnEmpty = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        lblMensaje = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Usuarios");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Nombre de Usuario:");

        btnPush.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnPush.setText("Push");
        btnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushActionPerformed(evt);
            }
        });

        btnPop.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnPop.setText("Pop");
        btnPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopActionPerformed(evt);
            }
        });

        btnPeek.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnPeek.setText("Peek");
        btnPeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeekActionPerformed(evt);
            }
        });

        btnSize.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSize.setText("Size");
        btnSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSizeActionPerformed(evt);
            }
        });

        btnEmpty.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEmpty.setText("Empty");
        btnEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmptyActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Buscar:");

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario"
            }
        ));
        tblUsuarios.setToolTipText("");
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Contraseña:");

        lblMensaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnNuevo)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                    .addComponent(txtContrasena))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPush)
                                    .addComponent(btnEmpty))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPop)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPeek)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSize))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAgregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnClear))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPush)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPop, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPeek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSize))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEmpty)
                            .addComponent(btnAgregar)
                            .addComponent(btnClear))
                        .addGap(9, 9, 9)))
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnEditar)
                            .addComponent(btnNuevo)
                            .addComponent(btnCancelar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushActionPerformed
        String usuario = txtNombreUsuario.getText().strip();
        if (usuario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un usuario.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            txtNombreUsuario.requestFocus();
            return;
        }

        String contrasenia = txtContrasena.getText().strip();
        if (contrasenia.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar una contraseña.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            txtContrasena.requestFocus();
            return;
        }
        
        if (crudUsuario.push(new Usuario(crudUsuario.obtenerUltimoId(), usuario, contrasenia))) {
            lblMensaje.setText("Usuario agregado correctamente: " + usuario);
        } else {
            lblMensaje.setText("No se agrego el usuario.");
        }
        limpiarCajas();
        limpiarTabla();
        listarUsuario();
    }//GEN-LAST:event_btnPushActionPerformed

    private void btnPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopActionPerformed
        if (crudUsuario.size() > 0) {
            Usuario usuarioEliminado = crudUsuario.pop();
            lblMensaje.setText("Usuario a eliminar en la cima: " + usuarioEliminado.getUsuario());
            modelo.setRowCount(0);
            listarUsuario();
        } else {
            JOptionPane.showMessageDialog(this, "La pila está vacía.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPopActionPerformed

    private void btnPeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeekActionPerformed
        if (crudUsuario.size() > 0) {
            Usuario ultimoUsuario = crudUsuario.peek();
            lblMensaje.setText("Último usuario en la pila: " + ultimoUsuario.getUsuario());
        } else {
            JOptionPane.showMessageDialog(this, "La pila está vacía.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPeekActionPerformed

    private void btnSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSizeActionPerformed
        limpiarTabla();
        listarUsuario();
        lblMensaje.setText("El tamaño de la pila es: " + crudUsuario.size());
    }//GEN-LAST:event_btnSizeActionPerformed

    private void btnEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmptyActionPerformed
        if (crudUsuario.isEmpty()) {
            lblMensaje.setText("La pila está vacía.");
        } else {
            lblMensaje.setText("La pila no está vacía.");
        }
    }//GEN-LAST:event_btnEmptyActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        crudUsuario.clear();
        lblMensaje.setText("La pila se ha vaciado.");
        modelo.setRowCount(0); // Limpia la tabla
        listarUsuario();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        guardar = true;
        txtNombreUsuario.setEnabled(true);
        txtContrasena.requestFocus();
        registroBotones(true);
        crudBotones(false);
        btnNuevo.setEnabled(false);
        lblMensaje.setText("");
        tblUsuarios.clearSelection();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblUsuarios.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
        } else {
            if (JOptionPane.showConfirmDialog(null, "Desea eliminar el Usuario", "Eliminar", JOptionPane.YES_NO_OPTION, 3) == 0) {
                if (crudUsuario.eliminar(new Usuario(idUsuario))) {
                    limpiarCajas();
                    listarUsuario();
                    lblMensaje.setText("El Usuario se eliminó correctamente");
                } else {
                    lblMensaje.setText("El Usuario NO se pudo eliminar");
                }
            }
            registroBotones(false);
            crudBotones(false);
            txtNombreUsuario.setText("");
            tblUsuarios.clearSelection();
        }
        limpiarTabla();
        listarUsuario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        habilitarCampo(true);
        lblMensaje.setText("");
        limpiarCajas();
        btnPush.setEnabled(true);
        btnCancelar.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCajas();
        crudBotones(false);
        btnPush.setEnabled(false);
        btnPop.setEnabled(false);
        btnPeek.setEnabled(false);
        lblMensaje.setText("");
        tblUsuarios.clearSelection();
        habilitarCampo(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblUsuariosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseReleased
        int fila = tblUsuarios.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null,
                    "Debe seleccionar una fila.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            habilitarCampo(false);
            idUsuario = Integer.parseInt(tblUsuarios.getValueAt(fila, 0).toString());
            txtNombreUsuario.setText(tblUsuarios.getValueAt(fila, 1).toString());
            lblMensaje.setText("");
            registroBotones(false);
            crudBotones(true);
            txtBuscar.setEnabled(false);
            btnCancelar.setEnabled(true);
            btnPop.setEnabled(true);
            btnPeek.setEnabled(true);

        }
    }//GEN-LAST:event_tblUsuariosMouseReleased

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String title = txtNombreUsuario.getText().strip();
        if (title.length() > 0 && title.length() <= 50) {
            if (guardar) {
                if (crudUsuario.actualizar(new Usuario(idUsuario, title))) {
                    
                    lblMensaje.setText("Se actualizo correctamente el color.");
                    habilitarCampo(false);
                    registroBotones(false);
                    crudBotones(false);
                    guardar = false;
                } else {
                    lblMensaje.setText("No se actualizo el color.");
                }
            } else {
                if (crudUsuario.obtenerId(title) == -1) {
                    if (crudUsuario.agregar(new Usuario(crudUsuario.obtenerUltimoId(), title))) {
                        lblMensaje.setText("Se agrego correctamente el color.");
                        habilitarCampo(false);
                        registroBotones(false);
                        crudBotones(false);
                    } else {
                        lblMensaje.setText("No se agrego el color.");
                    }
                } else {
                    lblMensaje.setText("No se agrego el color porque color ya existe.");
                    txtNombreUsuario.requestFocus();
                }
            }
            tblUsuarios.clearSelection();
            limpiarTabla();
            listarUsuario();
        } else {
            JOptionPane.showMessageDialog(null,
                    "Advertencia, El nombre del color debe estar entre 1 y 50 letras.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEmpty;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPeek;
    private javax.swing.JButton btnPop;
    private javax.swing.JButton btnPush;
    private javax.swing.JButton btnSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables

}
