package View;

import daoImpl.CategoriaDaoImpl;
import daoImpl.ColorDaoImpl;
import daoImpl.ContieneDaoImpl;
import daoImpl.MarcaDaoImpl;
import daoImpl.ProductoDaoImpl;
import daoImpl.TallaDaoImpl;
import daoImpl.VendidoDaoImpl;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import model.DetalleVenta;
import model.Nodo;


public class JimVendido extends javax.swing.JInternalFrame {
    private VendidoDaoImpl crudVendido;
    private DefaultTableModel modelo;
    private Object[] filaDatos;
    private ProductoDaoImpl IDaoProducto;
    private CategoriaDaoImpl IDaoCategoria;
    private MarcaDaoImpl IDaoMarca;
    private TallaDaoImpl IDaoTalla;
    private ColorDaoImpl IDaoColor;
    private ContieneDaoImpl IDaoContiene;
    
    public JimVendido() {
        initComponents();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.setSize(ancho, alto-106);
        crudVendido = new VendidoDaoImpl();
        modelo = new DefaultTableModel();
        filaDatos = new Object[8];
        IDaoProducto = new ProductoDaoImpl();
        IDaoCategoria = new CategoriaDaoImpl();
        IDaoMarca = new MarcaDaoImpl();
        IDaoTalla = new TallaDaoImpl();
        IDaoColor = new ColorDaoImpl();
        IDaoContiene = new ContieneDaoImpl();
        listarProductosVendidos();
    }
    
    private void listarProductosVendidos() {
        modelo = (DefaultTableModel) tblProductosVendidos.getModel();
        for (DetalleVenta devent : crudVendido.listar()) {
            if (devent != null ) {
                Nodo aux = IDaoContiene.inicio;
                while (aux != null) {
                    if (aux.getContiene().getIdContiene() == devent.getIdProducto()) {
                        filaDatos[0] = devent.getIdProducto();
                        filaDatos[1] = IDaoProducto.obtenerNombre(aux.getContiene().getIdProducto());
                        filaDatos[2] = IDaoCategoria.obtenerNombre(IDaoProducto.obtenerCategoria(aux.getContiene().getIdProducto()));
                        filaDatos[3] = IDaoMarca.obtenerNombre(aux.getContiene().getIdMarca());
                        filaDatos[4] = IDaoTalla.obtenerNombre(aux.getContiene().getIdTalla());
                        filaDatos[5] = IDaoColor.obtenerNombre(aux.getContiene().getIdColor());
                        filaDatos[6] = devent.getPrecio();
                        filaDatos[7] = devent.getCantidad();
                        modelo.addRow(filaDatos);
                    }
                    aux = aux.siguiente;
                }
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductosVendidos = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setText("Productos más Vendidos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 210, -1));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 210, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Mes:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Año:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 83, 32));

        tblProductosVendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Categoría", "Marca", "Talla", "Color", "Precio", "Cantidad"
            }
        ));
        jScrollPane2.setViewportView(tblProductosVendidos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 210, 1120, 291));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProductosVendidos;
    // End of variables declaration//GEN-END:variables
}
