package View;

import daoImpl.ClienteDaoImpl;
import daoImpl.VentaDaoImpl;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Venta;

public class JimVenta extends javax.swing.JInternalFrame {

    public static JDesktopPane jDesktopPane_menu;
    private VentaDaoImpl crudVenta;
    private DefaultTableModel modelo;
    private final Object[] filaDatos;
    private ClienteDaoImpl IDaoCliente;

    public JimVenta() {
        initComponents();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.setSize(ancho, alto - 106);
        crudVenta = new VentaDaoImpl();
        modelo = new DefaultTableModel();
        filaDatos = new Object[6];
        IDaoCliente = new ClienteDaoImpl();
        listarVentas();
    }
    
     private void limpiarTabla() {
        modelo = (DefaultTableModel) tblVentas.getModel();
        modelo.getDataVector().removeAllElements();
        tblVentas.removeAll();
    }

    public void listarVentas() {
        modelo = (DefaultTableModel) tblVentas.getModel();
        for (Venta ven : crudVenta.listar()) {
            if (ven != null && ven.isEstado() == true) {
                filaDatos[0] = ven.getIdVenta();
                filaDatos[1] = ven.getFecha();
                for (Cliente cli : IDaoCliente.listar()) {
                    if (cli != null && cli.getIdPersona()== ven.getIdCliente()) {
                        filaDatos[2] = cli.getNombres() + " " + cli.getApellidos();
                    }
                }
                filaDatos[3] = ven.getImpuestoTotal();
                filaDatos[4] = ven.getSubtotal();
                filaDatos[5] = ven.getTotal();
                modelo.addRow(filaDatos);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEditarDetalle = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBuscarVenta = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnVerDetalle = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditarDetalle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEditarDetalle.setText("Editar detalle");
        btnEditarDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDetalleActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, -1, 31));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Buscar:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setText("Ventas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        txtBuscarVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarVentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 332, 30));

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Cliente", "Total Impuestos", "Subtotal", "Total"
            }
        ));
        jScrollPane4.setViewportView(tblVentas);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 1136, 340));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, -1, 30));

        btnVerDetalle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnVerDetalle.setText("Ver detalle");
        btnVerDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetalleActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 120, 30));

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDetalleActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tblVentas.getSelectedRow();

        if (filaSeleccionada != -1) { // Verifica si hay una fila seleccionada
            // Obtén el ID de la compra desde la columna correspondiente
            Object value = tblVentas.getValueAt(filaSeleccionada, 0);
            if (value instanceof Integer) {
                int idVenta = (Integer) value;

                // Abre la ventana de detalle con los datos de la compra
                FrmMenu menu = (FrmMenu) SwingUtilities.getWindowAncestor(this);  // Obtén la ventana principal
                JDesktopPane jDesktopPane_menu = menu.getDesktopPane();  // Accede al JDesktopPane

                // Crear la vista de detalles de compra
                JimDetalleVenta vistaDVentas = new JimDetalleVenta();

                // Pasa el ID de la compra a la vista de detalles
                vistaDVentas.cargarDatosVentaEditar(idVenta);  // Método que carga los datos

                if (jDesktopPane_menu != null) {
                    jDesktopPane_menu.add(vistaDVentas); // Agrega el JInternalFrame al JDesktopPane
                    vistaDVentas.setVisible(true); // Haz visible el JInternalFrame

                    try {
                        vistaDVentas.setSelected(true); // Selecciona el JInternalFrame
                    } catch (java.beans.PropertyVetoException e) {
                        e.printStackTrace();
                    }
                } else {
                    System.out.println("El JDesktopPane no está inicializado.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "El valor de la columna ID no es válido.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una compra de la tabla.");
        }
        
    }//GEN-LAST:event_btnEditarDetalleActionPerformed

    private void txtBuscarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarVentaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        FrmMenu menu = (FrmMenu) SwingUtilities.getWindowAncestor(this);  // Obtiene la ventana principal (FrmMenu)
        JDesktopPane jDesktopPane_menu = menu.getDesktopPane();  // Accede al JDesktopPane

        // Crear la vista de detalles de venta
        JimDetalleVenta vistaDVentas = new JimDetalleVenta();

        // Asegúrate de que jDesktopPane_menu no sea null
        if (jDesktopPane_menu != null) {
            // Agregar el JInternalFrame (vistaDVentas) al JDesktopPane
            jDesktopPane_menu.add(vistaDVentas);

            // Hacer visible el JInternalFrame
            vistaDVentas.setVisible(true);

            // Establecer el JInternalFrame en el centro
            try {
                vistaDVentas.setSelected(true);  // Asegura que esté al frente
            } catch (java.beans.PropertyVetoException e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("El JDesktopPane no está inicializado.");
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnVerDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleActionPerformed
        int filaSeleccionada = tblVentas.getSelectedRow();

        if (filaSeleccionada != -1) { // Verifica si hay una fila seleccionada
            // Obtén el ID de la compra desde la columna correspondiente
            Object value = tblVentas.getValueAt(filaSeleccionada, 0);
            if (value instanceof Integer) {
                int idVenta = (Integer) value;

                // Abre la ventana de detalle con los datos de la compra
                FrmMenu menu = (FrmMenu) SwingUtilities.getWindowAncestor(this);  // Obtén la ventana principal
                JDesktopPane jDesktopPane_menu = menu.getDesktopPane();  // Accede al JDesktopPane

                // Crear la vista de detalles de compra
                JimDetalleVenta vistaDVenta = new JimDetalleVenta();

                // Pasa el ID de la compra a la vista de detalles
                vistaDVenta.cargarDatosVenta(idVenta);  // Método que carga los datos

                if (jDesktopPane_menu != null) {
                    jDesktopPane_menu.add(vistaDVenta); // Agrega el JInternalFrame al JDesktopPane
                    vistaDVenta.setVisible(true); // Haz visible el JInternalFrame

                    try {
                        vistaDVenta.setSelected(true); // Selecciona el JInternalFrame
                    } catch (java.beans.PropertyVetoException e) {
                        e.printStackTrace();
                    }
                } else {
                    System.out.println("El JDesktopPane no está inicializado.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "El valor de la columna ID no es válido.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una compra de la tabla.");
        }
    }//GEN-LAST:event_btnVerDetalleActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tblVentas.getSelectedRow();

        if (filaSeleccionada != -1) { // Verifica si hay una fila seleccionada
            // Obtén el ID de la compra desde la columna correspondiente
            Object value = tblVentas.getValueAt(filaSeleccionada, 0);
            if (value instanceof Integer) {
                int idVenta = (Integer) value;

                // Mostrar cuadro de confirmación
                int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar esta compra?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

                if (confirmacion == JOptionPane.YES_OPTION) {
                    // Crear un objeto Compra solo con el idCompra
                    Venta ventaAEliminar = new Venta();
                    ventaAEliminar.setIdVenta(idVenta);

                    // Llamar al método eliminar
                    if (crudVenta.eliminar(ventaAEliminar)) {
                        JOptionPane.showMessageDialog(this, "Compra eliminada con éxito.");
                        limpiarTabla();
                        listarVentas();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo eliminar la compra.");
                    }
                } else {
                    // Si el usuario selecciona 'No'
                    JOptionPane.showMessageDialog(this, "Eliminación cancelada.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "El valor de la columna ID no es válido.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una compra de la tabla.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarDetalle;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVerDetalle;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtBuscarVenta;
    // End of variables declaration//GEN-END:variables
}
